In [1]:
%load_ext autoreload
%autoreload 2
from core import RelicAlgorithm
import os
import logging
import pandas as pd

import sys

logging.basicConfig(format='%(funcName)s():%(lineno)d :%(levelname)s : %(message)s',
                     level=logging.INFO, stream=sys.stderr)
logger = logging.getLogger('Notebook')

In [2]:
RESULT_DIR = '/home/suhail/Projects/relic/primitives/python/generator/dataset/'
notebooks = [d for d in os.listdir(RESULT_DIR) if os.path.isdir(os.path.join(RESULT_DIR, d))]
nb = notebooks[0]

In [3]:
rl = RelicAlgorithm(RESULT_DIR, nb)
rl.logger.setLevel(logging.INFO)

__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130323

In [4]:
# Single Instance of Algorithm on nb:

nb = notebooks[25]
rl = RelicAlgorithm(RESULT_DIR, nb)
rl.set_initial_clusters()
rl.compute_intra_cluster_edges(weight_label='groupby')
rl.compute_component_pairs()
df = rl.compute_component_link_edges()

#rl.augment_ground_truth()
#rl.augment_inferred_graph()
#rl.augment_cluster_info()

__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135135

In [ ]:
rl.infer_link_edges()

In [ ]:
rl.weight_df

In [5]:
# For all notebooks
# No GT check here

all_results = pd.DataFrame()
RESULT_DIR = '/home/suhail/Projects/relic/primitives/python/generator/dataset/'
notebooks = [d for d in os.listdir(RESULT_DIR) if os.path.isdir(os.path.join(RESULT_DIR, d))]
nb = notebooks[0]

tie_breaker_options = {}

for nb in notebooks:
    rl = RelicAlgorithm(RESULT_DIR, nb)
    rl.set_initial_clusters()
    rl.compute_intra_cluster_edges(weight_label='groupby').dropna()
    rl.infer_link_edges()
    rl.augment_ground_truth()
    rl.augment_inferred_graph()
    rl.augment_cluster_info()
    df = rl.weight_df.copy().reset_index().rename({'index':'edge'}, axis=1)
    #df['nb'] = nb
    tie_breaker_options[nb] = rl.two_tie_edges
    all_results = all_results.append(df, ignore_index=True)

__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130323
tie_break_max_score():226 :WARNING : 10 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['12.csv', '5.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['16.csv', '19.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['22.csv', '27.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['0.csv', '8.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['8.csv', '4.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['25.csv', '31.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['7.csv', '1.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 7
infer_link_edges():206 :INFO : Adding edge #7: ['13.csv', '10.csv'], type groupby, weight 25.000000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 8
infer_link_edges():206 :INFO : Adding edge #8: ['11.csv', '13.csv'], type groupby, weight 25.000000
infer_link_edges():206 :INFO : Adding edge #9: ['8.csv', '6.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135026
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['16.csv', '14.csv'], type groupby, weight 7.333333
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['2.csv', '4.csv'], type groupby, weight 2.307692
infer_link_edges():206 :INFO : Adding edge #2: ['14.csv', '13.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135257
tie_break_max_score():226 :WARNING : 10 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['11.csv', '8.csv'], type groupby, weight 250.000000
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['5.csv', '8.csv'], type groupby, weight 250.000000
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['8.csv', '6.csv'], type groupby, weight 250.000000
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['7.csv', '14.csv'], type groupby, weight 250.000000
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['7.csv', '13.csv'], type groupby, weight 250.000000
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['17.csv', '8.csv'], type groupby, weight 222.500000
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['12.csv', '14.csv'], type groupby, weight 122.500000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 7
infer_link_edges():206 :INFO : Adding edge #7: ['14.csv', '15.csv'], type groupby, weight 122.500000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135331
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['34.csv', '37.csv'], type groupby, weight 7.692308
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['31.csv', '37.csv'], type groupby, weight 7.692308
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['33.csv', '45.csv'], type groupby, weight 1.369863
infer_link_edges():206 :INFO : Adding edge #3: ['0.csv', '1.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130017
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['3.csv', '2.csv'], type groupby, weight 200.000000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['2.csv', '4.csv'], type groupby, weight 200.000000
infer_link_edges():206 :INFO : Adding edge #2: ['7.csv', '14.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-141558
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['13.csv', '8.csv'], type groupby, weight 190.000000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['3.csv', '7.csv'], type groupby, weight 3.392857
infer_link_edges():206 :INFO : Adding edge #2: ['12.csv', '9.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-141746
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['16.csv', '10.csv'], type groupby, weight 47.619048
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['20.csv', '10.csv'], type groupby, weight 47.619048
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['27.csv', '10.csv'], type groupby, weight 47.619048
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['10.csv', '8.csv'], type groupby, weight 47.619048
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['46.csv', '43.csv'], type groupby, weight 19.607843
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['11.csv', '0.csv'], type groupby, weight 6.172840
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['29.csv', '30.csv'], type groupby, weight 1.003009
infer_link_edges():206 :INFO : Adding edge #7: ['40.csv', '37.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-141622
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['45.csv', '36.csv'], type groupby, weight 17.307692
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['26.csv', '36.csv'], type groupby, weight 4.444444
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['34.csv', '36.csv'], type groupby, weight 4.444444
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['17.csv', '1.csv'], type groupby, weight 4.424779
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['17.csv', '6.csv'], type groupby, weight 4.424779
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['17.csv', '2.csv'], type groupby, weight 4.424779
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['7.csv', '17.csv'], type groupby, weight 4.424779
infer_link_edges():206 :INFO : Adding edge #7: ['11.csv', '9.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-125847

__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130050
infer_link_edges():206 :INFO : Adding edge #0: ['21.csv', '16.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135121
tie_break_max_score():226 :WARNING : 12 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['3.csv', '12.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 11 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['12.csv', '1.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 10 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['12.csv', '0.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['12.csv', '5.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['3.csv', '13.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['12.csv', '4.csv'], type groupby, weight 21.500000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['11.csv', '12.csv'], type groupby, weight 21.500000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-125831
tie_break_max_score():226 :WARNING : 11 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['18.csv', '10.csv'], type groupby, weight 14.285714
tie_break_max_score():226 :WARNING : 10 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['18.csv', '2.csv'], type groupby, weight 14.285714
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['18.csv', '15.csv'], type groupby, weight 14.285714
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['18.csv', '9.csv'], type groupby, weight 14.285714
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['18.csv', '16.csv'], type groupby, weight 6.571429
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['10.csv', '6.csv'], type groupby, weight 4.761905
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['18.csv', '19.csv'], type groupby, weight 1.400000
infer_link_edges():206 :INFO : Adding edge #7: ['7.csv', '4.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130022
infer_link_edges():206 :INFO : Adding edge #0: ['16.csv', '14.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130336
infer_link_edges():206 :INFO : Adding edge #0: ['7.csv', '1.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135039
infer_link_edges():206 :INFO : Adding edge #0: ['23.csv', '14.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-141025
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['0.csv', '1.csv'], type groupby, weight 111.111111
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['5.csv', '1.csv'], type groupby, weight 111.111111
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['2.csv', '1.csv'], type groupby, weight 111.111111
infer_link_edges():206 :INFO : Adding edge #3: ['23.csv', '45.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-141044
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['23.csv', '33.csv'], type groupby, weight 10.000000
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['23.csv', '29.csv'], type groupby, weight 10.000000
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['33.csv', '24.csv'], type groupby, weight 8.000000
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['23.csv', '27.csv'], type groupby, weight 3.750000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['21.csv', '35.csv'], type groupby, weight 2.666667
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['21.csv', '19.csv'], type groupby, weight 1.500000
infer_link_edges():206 :INFO : Adding edge #6: ['41.csv', '48.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-140337
tie_break_max_score():226 :WARNING : 12 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['48.csv', '54.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 11 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['47.csv', '51.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 10 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['54.csv', '53.csv'], type groupby, weight 40.500000
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['34.csv', '37.csv'], type groupby, weight 38.000000
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['18.csv', '6.csv'], type groupby, weight 25.000000
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['9.csv', '6.csv'], type groupby, weight 25.000000
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['16.csv', '26.csv'], type groupby, weight 1.408451
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 7
infer_link_edges():206 :INFO : Adding edge #7: ['16.csv', '19.csv'], type groupby, weight 1.408451
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 8
infer_link_edges():206 :INFO : Adding edge #8: ['18.csv', '10.csv'], type groupby, weight 1.333333
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 9
infer_link_edges():206 :INFO : Adding edge #9: ['3.csv', '8.csv'], type groupby, weight 1.041667
infer_link_edges():206 :INFO : Adding edge #10: ['2.csv', '8.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130055
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['3.csv', '0.csv'], type groupby, weight 333.333333
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['0.csv', '1.csv'], type groupby, weight 333.333333
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['0.csv', '15.csv'], type groupby, weight 333.333333
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['9.csv', '0.csv'], type groupby, weight 333.333333
infer_link_edges():206 :INFO : Adding edge #4: ['13.csv', '0.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135126
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['10.csv', '2.csv'], type groupby, weight 50.000000

tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['0.csv', '2.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['3.csv', '13.csv'], type groupby, weight 16.666667
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['13.csv', '1.csv'], type groupby, weight 16.666667
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['5.csv', '13.csv'], type groupby, weight 8.500000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['9.csv', '13.csv'], type groupby, weight 8.500000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['3.csv', '4.csv'], type groupby, weight 1.020408
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130029
infer_link_edges():206 :INFO : Adding edge #0: ['11.csv', '12.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130224
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['19.csv', '17.csv'], type groupby, weight 31.250000
infer_link_edges():206 :INFO : Adding edge #1: ['18.csv', '12.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130252
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['14.csv', '0.csv'], type groupby, weight 500.000000
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['18.csv', '20.csv'], type groupby, weight 500.000000
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['0.csv', '1.csv'], type groupby, weight 250.000000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['16.csv', '17.csv'], type groupby, weight 38.461538
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['7.csv', '0.csv'], type groupby, weight 38.461538
infer_link_edges():206 :INFO : Adding edge #5: ['7.csv', '9.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130033
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['2.csv', '1.csv'], type groupby, weight 8.333333
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['0.csv', '2.csv'], type groupby, weight 8.333333
infer_link_edges():206 :INFO : Adding edge #2: ['22.csv', '10.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135320
infer_link_edges():206 :INFO : Adding edge #0: ['21.csv', '18.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135135
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['3.csv', '0.csv'], type groupby, weight 7.142857
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['0.csv', '1.csv'], type groupby, weight 4.000000
infer_link_edges():206 :INFO : Adding edge #2: ['3.csv', '2.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130201
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['19.csv', '22.csv'], type groupby, weight 29.461538
infer_link_edges():206 :INFO : Adding edge #1: ['22.csv', '20.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135112
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['0.csv', '1.csv'], type groupby, weight 8.264463
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['3.csv', '1.csv'], type groupby, weight 2.231405
infer_link_edges():206 :INFO : Adding edge #2: ['2.csv', '1.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135030
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['21.csv', '20.csv'], type groupby, weight 14.000000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['18.csv', '12.csv'], type groupby, weight 1.244444
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['18.csv', '16.csv'], type groupby, weight 1.244444
infer_link_edges():206 :INFO : Adding edge #3: ['18.csv', '19.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-125827
tie_break_max_score():226 :WARNING : 10 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['11.csv', '6.csv'], type groupby, weight 6.666667
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['16.csv', '6.csv'], type groupby, weight 6.666667
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['2.csv', '1.csv'], type groupby, weight 6.666667
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['8.csv', '1.csv'], type groupby, weight 6.666667
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['13.csv', '6.csv'], type groupby, weight 6.666667
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['11.csv', '12.csv'], type groupby, weight 5.000000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['3.csv', '2.csv'], type groupby, weight 3.333333
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130409
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['13.csv', '10.csv'], type groupby, weight 13.000000
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['25.csv', '24.csv'], type groupby, weight 11.111111
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['7.csv', '8.csv'], type groupby, weight 6.500000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['26.csv', '24.csv'], type groupby, weight 1.086957
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['41.csv', '36.csv'], type groupby, weight 1.086957
infer_link_edges():206 :INFO : Adding edge #5: ['41.csv', '39.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130038
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['23.csv', '7.csv'], type groupby, weight 46.500000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['5.csv', '4.csv'], type groupby, weight 1.075269
infer_link_edges():206 :INFO : Adding edge #2: ['5.csv', '2.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130355

tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['0.csv', '1.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['0.csv', '8.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['13.csv', '0.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['0.csv', '2.csv'], type groupby, weight 6.666667
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['48.csv', '38.csv'], type groupby, weight 3.000000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['42.csv', '37.csv'], type groupby, weight 3.000000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['55.csv', '37.csv'], type groupby, weight 3.000000
infer_link_edges():206 :INFO : Adding edge #7: ['2.csv', '4.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-125834
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['7.csv', '0.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['7.csv', '8.csv'], type groupby, weight 50.000000
infer_link_edges():206 :INFO : Adding edge #2: ['7.csv', '12.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135053
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['5.csv', '1.csv'], type groupby, weight 83.333333
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['5.csv', '2.csv'], type groupby, weight 83.333333
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['7.csv', '0.csv'], type groupby, weight 83.333333
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['3.csv', '1.csv'], type groupby, weight 38.461538
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['17.csv', '14.csv'], type groupby, weight 1.142857
infer_link_edges():206 :INFO : Adding edge #5: ['21.csv', '20.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-140352
tie_break_max_score():226 :WARNING : 18 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['5.csv', '51.csv'], type groupby, weight 165.000000
tie_break_max_score():226 :WARNING : 17 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['36.csv', '51.csv'], type groupby, weight 127.000000
tie_break_max_score():226 :WARNING : 16 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['46.csv', '51.csv'], type groupby, weight 127.000000
tie_break_max_score():226 :WARNING : 15 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['47.csv', '5.csv'], type groupby, weight 82.500000
tie_break_max_score():226 :WARNING : 12 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['51.csv', '8.csv'], type groupby, weight 38.000000
tie_break_max_score():226 :WARNING : 10 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['24.csv', '15.csv'], type groupby, weight 38.000000
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['33.csv', '31.csv'], type groupby, weight 11.500000
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 7
infer_link_edges():206 :INFO : Adding edge #7: ['10.csv', '51.csv'], type groupby, weight 8.000000
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 8
infer_link_edges():206 :INFO : Adding edge #8: ['9.csv', '51.csv'], type groupby, weight 8.000000
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 9
infer_link_edges():206 :INFO : Adding edge #9: ['0.csv', '1.csv'], type groupby, weight 5.181347
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 10
infer_link_edges():206 :INFO : Adding edge #10: ['18.csv', '7.csv'], type groupby, weight 2.171053
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 11
infer_link_edges():206 :INFO : Adding edge #11: ['21.csv', '29.csv'], type groupby, weight 1.310345
infer_link_edges():206 :INFO : Adding edge #12: ['29.csv', '13.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135245
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['0.csv', '1.csv'], type groupby, weight 6.097561
infer_link_edges():206 :INFO : Adding edge #1: ['9.csv', '1.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-141902
tie_break_max_score():226 :WARNING : 11 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['16.csv', '27.csv'], type groupby, weight 200.000000
tie_break_max_score():226 :WARNING : 10 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['20.csv', '27.csv'], type groupby, weight 200.000000
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['28.csv', '27.csv'], type groupby, weight 200.000000
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['35.csv', '30.csv'], type groupby, weight 150.000000
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['42.csv', '39.csv'], type groupby, weight 28.571429
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['32.csv', '35.csv'], type groupby, weight 16.500000
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['25.csv', '26.csv'], type groupby, weight 12.933333
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 7
infer_link_edges():206 :INFO : Adding edge #7: ['21.csv', '25.csv'], type groupby, weight 5.154639
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 8
infer_link_edges():206 :INFO : Adding edge #8: ['25.csv', '24.csv'], type groupby, weight 3.092784
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 9
infer_link_edges():206 :INFO : Adding edge #9: ['41.csv', '34.csv'], type groupby, weight 1.783784
infer_link_edges():206 :INFO : Adding edge #10: ['41.csv', '37.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130559
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['26.csv', '31.csv'], type groupby, weight 500.000000
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['19.csv', '15.csv'], type groupby, weight 10.866667
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['16.csv', '14.csv'], type groupby, weight 6.134969
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['13.csv', '10.csv'], type groupby, weight 6.134969
infer_link_edges():206 :INFO : Adding edge #4: ['11.csv', '13.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130432

tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['27.csv', '30.csv'], type groupby, weight 145.142857
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['27.csv', '29.csv'], type groupby, weight 145.142857
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['21.csv', '28.csv'], type groupby, weight 22.500000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['43.csv', '52.csv'], type groupby, weight 2.000000
infer_link_edges():206 :INFO : Adding edge #4: ['43.csv', '44.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-125817
tie_break_max_score():226 :WARNING : 10 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['7.csv', '9.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['2.csv', '1.csv'], type groupby, weight 11.400000
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['3.csv', '17.csv'], type groupby, weight 3.846154
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['12.csv', '17.csv'], type groupby, weight 3.846154
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['17.csv', '0.csv'], type groupby, weight 3.846154
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['17.csv', '6.csv'], type groupby, weight 3.846154
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['17.csv', '8.csv'], type groupby, weight 3.846154
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 7
infer_link_edges():206 :INFO : Adding edge #7: ['3.csv', '1.csv'], type groupby, weight 1.754386
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-141544
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['5.csv', '6.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['22.csv', '6.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['16.csv', '24.csv'], type groupby, weight 25.000000
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['14.csv', '24.csv'], type groupby, weight 25.000000
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['15.csv', '4.csv'], type groupby, weight 20.000000
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['11.csv', '15.csv'], type groupby, weight 20.000000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['29.csv', '5.csv'], type groupby, weight 14.285714
infer_link_edges():206 :INFO : Adding edge #7: ['32.csv', '29.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-140407
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['26.csv', '20.csv'], type groupby, weight 232.500000
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['16.csv', '15.csv'], type groupby, weight 29.062500
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['20.csv', '30.csv'], type groupby, weight 5.705521
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['21.csv', '34.csv'], type groupby, weight 5.705521
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['50.csv', '44.csv'], type groupby, weight 1.333333
infer_link_edges():206 :INFO : Adding edge #5: ['28.csv', '31.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135141
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135100
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['7.csv', '15.csv'], type groupby, weight 20.000000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['10.csv', '15.csv'], type groupby, weight 15.000000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['17.csv', '15.csv'], type groupby, weight 3.125000
infer_link_edges():206 :INFO : Adding edge #3: ['2.csv', '4.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-141508
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['3.csv', '1.csv'], type groupby, weight 50.000000
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['50.csv', '51.csv'], type groupby, weight 4.818182
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['9.csv', '13.csv'], type groupby, weight 2.000000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['34.csv', '17.csv'], type groupby, weight 1.545455
infer_link_edges():206 :INFO : Adding edge #4: ['27.csv', '17.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135035
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['5.csv', '1.csv'], type groupby, weight 50.000000
infer_link_edges():206 :INFO : Adding edge #1: ['0.csv', '2.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-141834
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['3.csv', '6.csv'], type groupby, weight 500.000000
infer_link_edges():206 :INFO : Adding edge #1: ['17.csv', '6.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130045
tie_break_max_score():226 :WARNING : 10 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['10.csv', '0.csv'], type groupby, weight 6.666667
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['9.csv', '0.csv'], type groupby, weight 6.666667
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['10.csv', '6.csv'], type groupby, weight 5.066667
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['7.csv', '10.csv'], type groupby, weight 5.066667
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['10.csv', '4.csv'], type groupby, weight 4.800000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['14.csv', '15.csv'], type groupby, weight 1.220339
infer_link_edges():206 :INFO : Adding edge #6: ['13.csv', '15.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135116

infer_link_edges():206 :INFO : Adding edge #0: ['0.csv', '2.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135356
/home/suhail/anaconda3/envs/relic/lib/python3.8/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['23.csv', '15.csv'], type groupby, weight 42.000000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['7.csv', '6.csv'], type groupby, weight 33.333333
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['32.csv', '38.csv'], type groupby, weight 1.449275
infer_link_edges():206 :INFO : Adding edge #3: ['15.csv', '6.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135045
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['12.csv', '6.csv'], type groupby, weight 14.000000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['12.csv', '10.csv'], type groupby, weight 12.600000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['11.csv', '12.csv'], type groupby, weight 12.600000
infer_link_edges():206 :INFO : Adding edge #3: ['0.csv', '6.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130103
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['16.csv', '15.csv'], type groupby, weight 142.857143
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['18.csv', '15.csv'], type groupby, weight 142.857143
infer_link_edges():206 :INFO : Adding edge #2: ['17.csv', '15.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-125837
infer_link_edges():206 :INFO : Adding edge #0: ['16.csv', '14.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-125822
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['21.csv', '16.csv'], type groupby, weight 14.000000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['11.csv', '5.csv'], type groupby, weight 1.282051
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['9.csv', '5.csv'], type groupby, weight 1.282051
infer_link_edges():206 :INFO : Adding edge #3: ['16.csv', '10.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-141524
tie_break_max_score():226 :WARNING : 9 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['46.csv', '47.csv'], type groupby, weight 563.000000
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['47.csv', '56.csv'], type groupby, weight 563.000000
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['47.csv', '52.csv'], type groupby, weight 456.000000
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['12.csv', '20.csv'], type groupby, weight 3.200000
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['0.csv', '2.csv'], type groupby, weight 2.500000
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['23.csv', '24.csv'], type groupby, weight 2.173913
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['42.csv', '27.csv'], type groupby, weight 1.408451
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 7
infer_link_edges():206 :INFO : Adding edge #7: ['42.csv', '29.csv'], type groupby, weight 1.408451
infer_link_edges():206 :INFO : Adding edge #8: ['42.csv', '30.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-140004
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['48.csv', '55.csv'], type groupby, weight 25.000000
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['11.csv', '9.csv'], type groupby, weight 14.666667
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['35.csv', '39.csv'], type groupby, weight 1.204819
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['46.csv', '43.csv'], type groupby, weight 1.204819
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['46.csv', '44.csv'], type groupby, weight 1.204819
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['9.csv', '4.csv'], type groupby, weight 1.181818
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['9.csv', '6.csv'], type groupby, weight 1.181818
infer_link_edges():206 :INFO : Adding edge #7: ['38.csv', '29.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135130
tie_break_max_score():226 :WARNING : 8 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['18.csv', '14.csv'], type groupby, weight 2.708333
tie_break_max_score():226 :WARNING : 7 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['0.csv', '1.csv'], type groupby, weight 2.272727
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['0.csv', '4.csv'], type groupby, weight 2.272727
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['0.csv', '2.csv'], type groupby, weight 2.272727
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 4
infer_link_edges():206 :INFO : Adding edge #4: ['16.csv', '19.csv'], type groupby, weight 1.756757
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 5
infer_link_edges():206 :INFO : Adding edge #5: ['19.csv', '13.csv'], type groupby, weight 1.756757
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 6
infer_link_edges():206 :INFO : Adding edge #6: ['16.csv', '17.csv'], type groupby, weight 1.226415
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-125842
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['23.csv', '20.csv'], type groupby, weight 4.016529
infer_link_edges():206 :INFO : Adding edge #1: ['17.csv', '14.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135326
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135048
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['0.csv', '8.csv'], type groupby, weight 500.000000
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['9.csv', '14.csv'], type groupby, weight 39.000000
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 2

infer_link_edges():206 :INFO : Adding edge #2: ['18.csv', '0.csv'], type groupby, weight 38.461538
infer_link_edges():206 :INFO : Adding edge #3: ['21.csv', '5.csv'], type groupby, weight 1.000000
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-135057
tie_break_max_score():226 :WARNING : 6 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['3.csv', '0.csv'], type groupby, weight 142.857143
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['0.csv', '4.csv'], type groupby, weight 142.857143
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['3.csv', '2.csv'], type groupby, weight 142.857143
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['12.csv', '0.csv'], type groupby, weight 83.333333
__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200817-130257
tie_break_max_score():226 :WARNING : 5 TieBreaker Candidates for edge 0
infer_link_edges():206 :INFO : Adding edge #0: ['42.csv', '51.csv'], type groupby, weight 8.333333
tie_break_max_score():226 :WARNING : 4 TieBreaker Candidates for edge 1
infer_link_edges():206 :INFO : Adding edge #1: ['14.csv', '37.csv'], type groupby, weight 1.298701
tie_break_max_score():226 :WARNING : 3 TieBreaker Candidates for edge 2
infer_link_edges():206 :INFO : Adding edge #2: ['8.csv', '37.csv'], type groupby, weight 1.298701
tie_break_max_score():226 :WARNING : 2 TieBreaker Candidates for edge 3
infer_link_edges():206 :INFO : Adding edge #3: ['7.csv', '4.csv'], type groupby, weight 1.298701
infer_link_edges():206 :INFO : Adding edge #4: ['9.csv', '37.csv'], type groupby, weight 1.000000

In [6]:
all_results = all_results.rename({'index':'edge'}, axis=1)

In [7]:
tie_breaker_options

{'20200817-130323': {0: (12.csv, 5.csv)     50.0
  (16.csv, 19.csv)    50.0
  (22.csv, 27.csv)    50.0
  (0.csv, 8.csv)      50.0
  (8.csv, 4.csv)      50.0
  (25.csv, 31.csv)    50.0
  (7.csv, 1.csv)      50.0
  (13.csv, 10.csv)     NaN
  (11.csv, 13.csv)     NaN
  (8.csv, 6.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  1: (16.csv, 19.csv)    50.0
  (22.csv, 27.csv)    50.0
  (0.csv, 8.csv)      50.0
  (8.csv, 4.csv)      50.0
  (25.csv, 31.csv)    50.0
  (7.csv, 1.csv)      50.0
  (13.csv, 10.csv)     NaN
  (11.csv, 13.csv)     NaN
  (8.csv, 6.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  2: (22.csv, 27.csv)    50.0
  (0.csv, 8.csv)      50.0
  (8.csv, 4.csv)      50.0
  (25.csv, 31.csv)    50.0
  (7.csv, 1.csv)      50.0
  (13.csv, 10.csv)     NaN
  (11.csv, 13.csv)     NaN
  (8.csv, 6.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  3: (0.csv, 8.csv)      50.0
  (8.csv, 4.csv)      50.0
  (25.csv, 31.csv)    50.0
  (7.csv, 1.csv)      50.0
  (13.csv, 10.csv)     NaN
  (11.csv, 13.csv)     NaN
  (8.csv, 6.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  4: (8.csv, 4.csv)      50.0
  (25.csv, 31.csv)    50.0
  (7.csv, 1.csv)      50.0
  (13.csv, 10.csv)     NaN
  (11.csv, 13.csv)     NaN
  (8.csv, 6.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  5: (25.csv, 31.csv)    50.0
  (7.csv, 1.csv)      50.0
  (13.csv, 10.csv)     NaN
  (11.csv, 13.csv)     NaN
  (8.csv, 6.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  6: (7.csv, 1.csv)      50.0
  (13.csv, 10.csv)     NaN
  (11.csv, 13.csv)     NaN
  (8.csv, 6.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  7: (13.csv, 10.csv)    25.0
  (11.csv, 13.csv)    25.0
  (8.csv, 6.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  8: (11.csv, 13.csv)    25.0
  (8.csv, 6.csv)       NaN
  Name: contraction_ratio, dtype: float64},
 '20200817-135026': {0: (16.csv, 14.csv)    7.333333
  (2.csv, 4.csv)           NaN
  (14.csv, 13.csv)         NaN
  Name: contraction_ratio, dtype: float64,
  1: (2.csv, 4.csv)      2.307692
  (14.csv, 13.csv)         NaN
  Name: contraction_ratio, dtype: float64},
 '20200817-135257': {0: (11.csv, 8.csv)     250.0
  (5.csv, 8.csv)      250.0
  (8.csv, 6.csv)      250.0
  (7.csv, 14.csv)     250.0
  (7.csv, 13.csv)     250.0
  (17.csv, 8.csv)       NaN
  (12.csv, 14.csv)      NaN
  (14.csv, 15.csv)      NaN
  (12.csv, 13.csv)      NaN
  (13.csv, 15.csv)      NaN
  Name: contraction_ratio, dtype: float64,
  1: (5.csv, 8.csv)      250.0
  (8.csv, 6.csv)      250.0
  (7.csv, 14.csv)     250.0
  (7.csv, 13.csv)     250.0
  (17.csv, 8.csv)       NaN
  (12.csv, 14.csv)      NaN
  (14.csv, 15.csv)      NaN
  (12.csv, 13.csv)      NaN
  (13.csv, 15.csv)      NaN
  Name: contraction_ratio, dtype: float64,
  2: (8.csv, 6.csv)      250.0
  (7.csv, 14.csv)     250.0
  (7.csv, 13.csv)     250.0
  (17.csv, 8.csv)       NaN
  (12.csv, 14.csv)      NaN
  (14.csv, 15.csv)      NaN
  (12.csv, 13.csv)      NaN
  (13.csv, 15.csv)      NaN
  Name: contraction_ratio, dtype: float64,
  3: (7.csv, 14.csv)     250.0
  (7.csv, 13.csv)     250.0
  (17.csv, 8.csv)       NaN
  (12.csv, 14.csv)      NaN
  (14.csv, 15.csv)      NaN
  (12.csv, 13.csv)      NaN
  (13.csv, 15.csv)      NaN
  Name: contraction_ratio, dtype: float64,
  4: (7.csv, 13.csv)     250.0
  (17.csv, 8.csv)       NaN
  (12.csv, 14.csv)      NaN
  (14.csv, 15.csv)      NaN
  (12.csv, 13.csv)      NaN
  (13.csv, 15.csv)      NaN
  Name: contraction_ratio, dtype: float64,
  5: (17.csv, 8.csv)     222.5
  (12.csv, 14.csv)      NaN
  (14.csv, 15.csv)      NaN
  (12.csv, 13.csv)      NaN
  (13.csv, 15.csv)      NaN
  Name: contraction_ratio, dtype: float64,
  6: (12.csv, 14.csv)    122.5
  (14.csv, 15.csv)    122.5
  (12.csv, 13.csv)    122.5
  (13.csv, 15.csv)    122.5
  Name: contraction_ratio, dtype: float64,
  7: (14.csv, 15.csv)    122.5
  (13.csv, 15.csv)    122.5
  Name: contraction_ratio, dtype: float64},
 '20200817-135331': {0: (34.csv, 37.csv)    7.692308
  (31.csv, 37.csv)    7.692308
  (33.csv, 45.csv)         NaN
  (0.csv, 1.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  1: (31.csv, 37.csv)    7.692308
  (33.csv, 45.csv)         NaN
  (0.csv, 1.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  2: (33.csv, 45.csv)    1.369863
  (0.csv, 1.csv)           NaN
  Name: contraction_ratio, dtype: float64},
 '20200817-130017': {0: (3.csv, 2.csv)     200.0
  (2.csv, 4.csv)     200.0
  (7.csv, 14.csv)    200.0
  Name: contraction_ratio, dtype: float64,
  1: (2.csv, 4.csv)     200.0
  (7.csv, 14.csv)    200.0
  Name: contraction_ratio, dtype: float64},
 '20200817-141558': {0: (13.csv, 8.csv)    190.0
  (3.csv, 7.csv)       NaN
  (12.csv, 9.csv)      NaN
  Name: contraction_ratio, dtype: float64,
  1: (3.csv, 7.csv)     3.392857
  (12.csv, 9.csv)         NaN
  Name: contraction_ratio, dtype: float64},
 '20200817-141746': {0: (16.csv, 10.csv)    47.619048
  (20.csv, 10.csv)    47.619048
  (27.csv, 10.csv)    47.619048
  (10.csv, 8.csv)     47.619048
  (46.csv, 43.csv)          NaN
  (11.csv, 0.csv)           NaN
  (29.csv, 30.csv)          NaN
  (40.csv, 37.csv)          NaN
  Name: contraction_ratio, dtype: float64,
  1: (20.csv, 10.csv)    47.619048
  (27.csv, 10.csv)    47.619048
  (10.csv, 8.csv)     47.619048
  (46.csv, 43.csv)          NaN
  (11.csv, 0.csv)           NaN
  (29.csv, 30.csv)          NaN
  (40.csv, 37.csv)          NaN
  Name: contraction_ratio, dtype: float64,
  2: (27.csv, 10.csv)    47.619048
  (10.csv, 8.csv)     47.619048
  (46.csv, 43.csv)          NaN
  (11.csv, 0.csv)           NaN
  (29.csv, 30.csv)          NaN
  (40.csv, 37.csv)          NaN
  Name: contraction_ratio, dtype: float64,
  3: (10.csv, 8.csv)     47.619048
  (46.csv, 43.csv)          NaN
  (11.csv, 0.csv)           NaN
  (29.csv, 30.csv)          NaN
  (40.csv, 37.csv)          NaN
  Name: contraction_ratio, dtype: float64,
  4: (46.csv, 43.csv)    19.607843
  (11.csv, 0.csv)           NaN
  (29.csv, 30.csv)          NaN
  (40.csv, 37.csv)          NaN
  Name: contraction_ratio, dtype: float64,
  5: (11.csv, 0.csv)     6.17284
  (29.csv, 30.csv)        NaN
  (40.csv, 37.csv)        NaN
  Name: contraction_ratio, dtype: float64,
  6: (29.csv, 30.csv)    1.003009
  (40.csv, 37.csv)    1.003009
  Name: contraction_ratio, dtype: float64},
 '20200817-141622': {0: (45.csv, 36.csv)    17.307692
  (26.csv, 36.csv)          NaN
  (34.csv, 36.csv)          NaN
  (17.csv, 1.csv)           NaN
  (17.csv, 6.csv)           NaN
  (17.csv, 2.csv)           NaN
  (7.csv, 17.csv)           NaN
  (11.csv, 9.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  1: (26.csv, 36.csv)    4.444444
  (34.csv, 36.csv)    4.444444
  (17.csv, 1.csv)          NaN
  (17.csv, 6.csv)          NaN
  (17.csv, 2.csv)          NaN
  (7.csv, 17.csv)          NaN
  (11.csv, 9.csv)          NaN
  Name: contraction_ratio, dtype: float64,
  2: (34.csv, 36.csv)    4.444444
  (17.csv, 1.csv)          NaN
  (17.csv, 6.csv)          NaN
  (17.csv, 2.csv)          NaN
  (7.csv, 17.csv)          NaN
  (11.csv, 9.csv)          NaN
  Name: contraction_ratio, dtype: float64,
  3: (17.csv, 1.csv)    4.424779
  (17.csv, 6.csv)    4.424779
  (17.csv, 2.csv)    4.424779
  (7.csv, 17.csv)    4.424779
  (11.csv, 9.csv)    4.424779
  Name: contraction_ratio, dtype: float64,
  4: (17.csv, 6.csv)    4.424779
  (17.csv, 2.csv)    4.424779
  (7.csv, 17.csv)    4.424779
  (11.csv, 9.csv)    4.424779
  Name: contraction_ratio, dtype: float64,
  5: (17.csv, 2.csv)    4.424779
  (7.csv, 17.csv)    4.424779
  (11.csv, 9.csv)    4.424779
  Name: contraction_ratio, dtype: float64,
  6: (7.csv, 17.csv)    4.424779
  (11.csv, 9.csv)    4.424779
  Name: contraction_ratio, dtype: float64},
 '20200817-125847': {},
 '20200817-130050': {},
 '20200817-135121': {0: (3.csv, 12.csv)     50.0
  (12.csv, 1.csv)     50.0
  (12.csv, 0.csv)     50.0
  (12.csv, 5.csv)     50.0
  (3.csv, 13.csv)     50.0
  (13.csv, 1.csv)     50.0
  (13.csv, 0.csv)     50.0
  (5.csv, 13.csv)     50.0
  (12.csv, 4.csv)      NaN
  (11.csv, 12.csv)     NaN
  (13.csv, 4.csv)      NaN
  (11.csv, 13.csv)     NaN
  Name: contraction_ratio, dtype: float64,
  1: (12.csv, 1.csv)     50.0
  (12.csv, 0.csv)     50.0
  (12.csv, 5.csv)     50.0
  (3.csv, 13.csv)     50.0
  (13.csv, 1.csv)     50.0
  (13.csv, 0.csv)     50.0
  (5.csv, 13.csv)     50.0
  (12.csv, 4.csv)      NaN
  (11.csv, 12.csv)     NaN
  (13.csv, 4.csv)      NaN
  (11.csv, 13.csv)     NaN
  Name: contraction_ratio, dtype: float64,
  2: (12.csv, 0.csv)     50.0
  (12.csv, 5.csv)     50.0
  (3.csv, 13.csv)     50.0
  (13.csv, 1.csv)     50.0
  (13.csv, 0.csv)     50.0
  (5.csv, 13.csv)     50.0
  (12.csv, 4.csv)      NaN
  (11.csv, 12.csv)     NaN
  (13.csv, 4.csv)      NaN
  (11.csv, 13.csv)     NaN
  Name: contraction_ratio, dtype: float64,
  3: (12.csv, 5.csv)     50.0
  (3.csv, 13.csv)     50.0
  (13.csv, 1.csv)     50.0
  (13.csv, 0.csv)     50.0
  (5.csv, 13.csv)     50.0
  (12.csv, 4.csv)      NaN
  (11.csv, 12.csv)     NaN
  (13.csv, 4.csv)      NaN
  (11.csv, 13.csv)     NaN
  Name: contraction_ratio, dtype: float64,
  4: (3.csv, 13.csv)     50.0
  (13.csv, 1.csv)     50.0
  (13.csv, 0.csv)     50.0
  (5.csv, 13.csv)     50.0
  (12.csv, 4.csv)      NaN
  (11.csv, 12.csv)     NaN
  (13.csv, 4.csv)      NaN
  (11.csv, 13.csv)     NaN
  Name: contraction_ratio, dtype: float64,
  5: (12.csv, 4.csv)     21.5
  (11.csv, 12.csv)    21.5
  (13.csv, 4.csv)     21.5
  (11.csv, 13.csv)    21.5
  Name: contraction_ratio, dtype: float64,
  6: (11.csv, 12.csv)    21.5
  (11.csv, 13.csv)    21.5
  Name: contraction_ratio, dtype: float64},
 '20200817-125831': {0: (18.csv, 10.csv)    14.285714
  (18.csv, 2.csv)     14.285714
  (18.csv, 15.csv)    14.285714
  (18.csv, 9.csv)     14.285714
  (18.csv, 16.csv)          NaN
  (10.csv, 6.csv)           NaN
  (2.csv, 6.csv)            NaN
  (15.csv, 6.csv)           NaN
  (9.csv, 6.csv)            NaN
  (18.csv, 19.csv)          NaN
  (7.csv, 4.csv)            NaN
  Name: contraction_ratio, dtype: float64,
  1: (18.csv, 2.csv)     14.285714
  (18.csv, 15.csv)    14.285714
  (18.csv, 9.csv)     14.285714
  (18.csv, 16.csv)          NaN
  (10.csv, 6.csv)           NaN
  (2.csv, 6.csv)            NaN
  (15.csv, 6.csv)           NaN
  (9.csv, 6.csv)            NaN
  (18.csv, 19.csv)          NaN
  (7.csv, 4.csv)            NaN
  Name: contraction_ratio, dtype: float64,
  2: (18.csv, 15.csv)    14.285714
  (18.csv, 9.csv)     14.285714
  (18.csv, 16.csv)          NaN
  (10.csv, 6.csv)           NaN
  (2.csv, 6.csv)            NaN
  (15.csv, 6.csv)           NaN
  (9.csv, 6.csv)            NaN
  (18.csv, 19.csv)          NaN
  (7.csv, 4.csv)            NaN
  Name: contraction_ratio, dtype: float64,
  3: (18.csv, 9.csv)     14.285714
  (18.csv, 16.csv)          NaN
  (10.csv, 6.csv)           NaN
  (2.csv, 6.csv)            NaN
  (15.csv, 6.csv)           NaN
  (9.csv, 6.csv)            NaN
  (18.csv, 19.csv)          NaN
  (7.csv, 4.csv)            NaN
  Name: contraction_ratio, dtype: float64,
  4: (18.csv, 16.csv)    6.571429
  (10.csv, 6.csv)          NaN
  (2.csv, 6.csv)           NaN
  (15.csv, 6.csv)          NaN
  (9.csv, 6.csv)           NaN
  (18.csv, 19.csv)         NaN
  (7.csv, 4.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  5: (10.csv, 6.csv)     4.761905
  (2.csv, 6.csv)      4.761905
  (15.csv, 6.csv)     4.761905
  (9.csv, 6.csv)      4.761905
  (18.csv, 19.csv)         NaN
  (7.csv, 4.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  6: (18.csv, 19.csv)    1.4
  (7.csv, 4.csv)      NaN
  Name: contraction_ratio, dtype: float64},
 '20200817-130022': {},
 '20200817-130336': {},
 '20200817-135039': {},
 '20200817-141025': {0: (0.csv, 1.csv)      111.111111
  (5.csv, 1.csv)      111.111111
  (2.csv, 1.csv)      111.111111
  (23.csv, 45.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  1: (5.csv, 1.csv)      111.111111
  (2.csv, 1.csv)      111.111111
  (23.csv, 45.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  2: (2.csv, 1.csv)      111.111111
  (23.csv, 45.csv)           NaN
  Name: contraction_ratio, dtype: float64},
 '20200817-141044': {0: (23.csv, 33.csv)    10.0
  (23.csv, 29.csv)    10.0
  (33.csv, 24.csv)     NaN
  (29.csv, 24.csv)     NaN
  (23.csv, 27.csv)     NaN
  (27.csv, 24.csv)     NaN
  (21.csv, 35.csv)     NaN
  (21.csv, 19.csv)     NaN
  (41.csv, 48.csv)     NaN
  Name: contraction_ratio, dtype: float64,
  1: (23.csv, 29.csv)    10.0
  (33.csv, 24.csv)     NaN
  (29.csv, 24.csv)     NaN
  (23.csv, 27.csv)     NaN
  (27.csv, 24.csv)     NaN
  (21.csv, 35.csv)     NaN
  (21.csv, 19.csv)     NaN
  (41.csv, 48.csv)     NaN
  Name: contraction_ratio, dtype: float64,
  2: (33.csv, 24.csv)    8.0
  (29.csv, 24.csv)    8.0
  (23.csv, 27.csv)    NaN
  (27.csv, 24.csv)    NaN
  (21.csv, 35.csv)    NaN
  (21.csv, 19.csv)    NaN
  (41.csv, 48.csv)    NaN
  Name: contraction_ratio, dtype: float64,
  3: (23.csv, 27.csv)    3.75
  (27.csv, 24.csv)     NaN
  (21.csv, 35.csv)     NaN
  (21.csv, 19.csv)     NaN
  (41.csv, 48.csv)     NaN
  Name: contraction_ratio, dtype: float64,
  4: (21.csv, 35.csv)    2.666667
  (21.csv, 19.csv)         NaN
  (41.csv, 48.csv)         NaN
  Name: contraction_ratio, dtype: float64,
  5: (21.csv, 19.csv)    1.5
  (41.csv, 48.csv)    1.5
  Name: contraction_ratio, dtype: float64},
 '20200817-140337': {0: (48.csv, 54.csv)    50.0
  (47.csv, 51.csv)    50.0
  (54.csv, 53.csv)     NaN
  (34.csv, 37.csv)     NaN
  (18.csv, 6.csv)      NaN
  (9.csv, 6.csv)       NaN
  (16.csv, 26.csv)     NaN
  (16.csv, 19.csv)     NaN
  (18.csv, 10.csv)     NaN
  (9.csv, 10.csv)      NaN
  (3.csv, 8.csv)       NaN
  (2.csv, 8.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  1: (47.csv, 51.csv)    50.0
  (54.csv, 53.csv)     NaN
  (34.csv, 37.csv)     NaN
  (18.csv, 6.csv)      NaN
  (9.csv, 6.csv)       NaN
  (16.csv, 26.csv)     NaN
  (16.csv, 19.csv)     NaN
  (18.csv, 10.csv)     NaN
  (9.csv, 10.csv)      NaN
  (3.csv, 8.csv)       NaN
  (2.csv, 8.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  2: (54.csv, 53.csv)    40.5
  (34.csv, 37.csv)     NaN
  (18.csv, 6.csv)      NaN
  (9.csv, 6.csv)       NaN
  (16.csv, 26.csv)     NaN
  (16.csv, 19.csv)     NaN
  (18.csv, 10.csv)     NaN
  (9.csv, 10.csv)      NaN
  (3.csv, 8.csv)       NaN
  (2.csv, 8.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  3: (34.csv, 37.csv)    38.0
  (18.csv, 6.csv)      NaN
  (9.csv, 6.csv)       NaN
  (16.csv, 26.csv)     NaN
  (16.csv, 19.csv)     NaN
  (18.csv, 10.csv)     NaN
  (9.csv, 10.csv)      NaN
  (3.csv, 8.csv)       NaN
  (2.csv, 8.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  4: (18.csv, 6.csv)     25.0
  (9.csv, 6.csv)      25.0
  (16.csv, 26.csv)     NaN
  (16.csv, 19.csv)     NaN
  (18.csv, 10.csv)     NaN
  (9.csv, 10.csv)      NaN
  (3.csv, 8.csv)       NaN
  (2.csv, 8.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  5: (9.csv, 6.csv)      25.0
  (16.csv, 26.csv)     NaN
  (16.csv, 19.csv)     NaN
  (18.csv, 10.csv)     NaN
  (9.csv, 10.csv)      NaN
  (3.csv, 8.csv)       NaN
  (2.csv, 8.csv)       NaN
  Name: contraction_ratio, dtype: float64,
  6: (16.csv, 26.csv)    1.408451
  (16.csv, 19.csv)    1.408451
  (18.csv, 10.csv)         NaN
  (9.csv, 10.csv)          NaN
  (3.csv, 8.csv)           NaN
  (2.csv, 8.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  7: (16.csv, 19.csv)    1.408451
  (18.csv, 10.csv)         NaN
  (9.csv, 10.csv)          NaN
  (3.csv, 8.csv)           NaN
  (2.csv, 8.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  8: (18.csv, 10.csv)    1.333333
  (9.csv, 10.csv)     1.333333
  (3.csv, 8.csv)           NaN
  (2.csv, 8.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  9: (3.csv, 8.csv)    1.041667
  (2.csv, 8.csv)    1.041667
  Name: contraction_ratio, dtype: float64},
 '20200817-130055': {0: (3.csv, 0.csv)     333.333333
  (0.csv, 1.csv)     333.333333
  (0.csv, 15.csv)    333.333333
  (9.csv, 0.csv)     333.333333
  (13.csv, 0.csv)    333.333333
  Name: contraction_ratio, dtype: float64,
  1: (0.csv, 1.csv)     333.333333
  (0.csv, 15.csv)    333.333333
  (9.csv, 0.csv)     333.333333
  (13.csv, 0.csv)    333.333333
  Name: contraction_ratio, dtype: float64,
  2: (0.csv, 15.csv)    333.333333
  (9.csv, 0.csv)     333.333333
  (13.csv, 0.csv)    333.333333
  Name: contraction_ratio, dtype: float64,
  3: (9.csv, 0.csv)     333.333333
  (13.csv, 0.csv)    333.333333
  Name: contraction_ratio, dtype: float64},
 '20200817-135126': {0: (10.csv, 2.csv)    50.0
  (0.csv, 2.csv)     50.0
  (3.csv, 13.csv)     NaN
  (13.csv, 1.csv)     NaN
  (5.csv, 13.csv)     NaN
  (9.csv, 13.csv)     NaN
  (3.csv, 4.csv)      NaN
  (1.csv, 4.csv)      NaN
  Name: contraction_ratio, dtype: float64,
  1: (0.csv, 2.csv)     50.0
  (3.csv, 13.csv)     NaN
  (13.csv, 1.csv)     NaN
  (5.csv, 13.csv)     NaN
  (9.csv, 13.csv)     NaN
  (3.csv, 4.csv)      NaN
  (1.csv, 4.csv)      NaN
  Name: contraction_ratio, dtype: float64,
  2: (3.csv, 13.csv)    16.666667
  (13.csv, 1.csv)    16.666667
  (5.csv, 13.csv)          NaN
  (9.csv, 13.csv)          NaN
  (3.csv, 4.csv)           NaN
  (1.csv, 4.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  3: (13.csv, 1.csv)    16.666667
  (5.csv, 13.csv)          NaN
  (9.csv, 13.csv)          NaN
  (3.csv, 4.csv)           NaN
  (1.csv, 4.csv)           NaN
  Name: contraction_ratio, dtype: float64,
  4: (5.csv, 13.csv)    8.5
  (9.csv, 13.csv)    8.5
  (3.csv, 4.csv)     NaN
  (1.csv, 4.csv)     NaN
  Name: contraction_ratio, dtype: float64,
  5: (9.csv, 13.csv)    8.5
  (3.csv, 4.csv)     NaN
  (1.csv, 4.csv)     NaN
  Name: contraction_ratio, dtype: float64,
  6: (3.csv, 4.csv)    1.020408
  (1.csv, 4.csv)    1.020408
  Name: contraction_ratio, dtype: float64},
 '20200817-130029': {},
 '20200817-130224': {0: (19.csv, 17.csv)    31.25
  (18.csv, 12.csv)      NaN
  Name: contraction_ratio, dtype: float64},
 '20200817-130252': {0: (14.csv, 0.csv)     500.0
  (18.csv, 20.csv)    500.0
  (0.csv, 1.csv)        NaN
  (16.csv, 17.csv)      NaN
  (7.csv, 0.csv)        NaN
  (7.csv, 9.csv)        NaN
  Name: contraction_ratio, dtype: float64,
  1: (18.csv, 20.csv)    500.0
  (0.csv, 1.csv)        NaN
  (16.csv, 17.csv)      NaN
  (7.csv, 0.csv)        NaN
  (7.csv, 9.csv)        NaN
  Name: contraction_ratio, dtype: float64,
  2: (0.csv, 1.csv)      250.0
  (16.csv, 17.csv)      NaN
  (7.csv, 0.csv)        NaN
  (7.csv, 9.csv)        NaN
  Name: contraction_ratio, dtype: float64,
  3: (16.csv, 17.csv)    38.461538
  (7.csv, 0.csv)      38.461538
  (7.csv, 9.csv)            NaN
  Name: contraction_ratio, dtype: float64,
  4: (7.csv, 0.csv)    38.461538
  (7.csv, 9.csv)          NaN
  Name: contraction_ratio, dtype: float64},
 '20200817-130033': {0: (2.csv, 1.csv)      8.333333
  (0.csv, 2.csv)      8.333333
  (22.csv, 10.csv)         NaN
  Name: contraction_ratio, dtype: float64,
  1: (0.csv, 2.csv)      8.333333
  (22.csv, 10.csv)         NaN
  Name: contraction_ratio, dtype: float64},
 '20200817-135320': {},
 '20200817-135135': {0: (3.csv, 0.csv)    7.142857
  (0.csv, 1.csv)         NaN
  (3.csv, 2.csv)         NaN
  Name: contraction_ratio, dtype: float64,
  1: (0.csv, 1.csv)    4.0
  (3.csv, 2.csv)    NaN
  Name: contraction_ratio, dtype: float64},
 '20200817-130201': {0: (19.csv, 22.csv)    29.461538
  (22.csv, 20.csv)          NaN
  Name: contraction_ratio, dtype: float64},
 '20200817-135112': {0: (0.csv, 1.csv)    8.264463
  (3.csv, 1.csv)         NaN
  (2.csv, 1.csv)         NaN
  Name: contraction_ratio, dtype: float64,
  1: (3.csv, 1.csv)    2.231405
  (2.csv, 1.csv)    2.231405
  Name: contraction_ratio, dtype: float64},
 '20200817-135030': {0: (21.csv, 20.csv)    14.0
  (18.csv, 12.csv)     NaN
  (18.csv, 16.csv)     NaN
  (18.csv, 19.csv)     NaN

# Analysis Section

In [8]:
from lineage import similarity
def inspect_dataframes(df, ix):
    src = list(df.loc[ix]['edge'])[0]
    dst = list(df.loc[ix]['edge'])[1]
    df_dict = similarity.load_dataset_dir(RESULT_DIR+df.loc[ix]['nb']+'/artifacts/', '*.csv', index_col=0)
    display(df_dict[src])
    display(df_dict[dst])
    return df_dict[src], df_dict[dst], src, dst, df.loc[ix]['nb'], df_dict

In [10]:
import qgrid
#edges = groupby_edges
qgrid_widget = qgrid.show_grid(all_results, show_toolbar=True)
qgrid_widget

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': True, 'defau…

In [17]:
df1, df2, src, dst, nb_name, df_dict = inspect_dataframes(all_results, 37407)

,safe_color_name,md5,ean,iban,pystr,ascii_free_email,pybool,postcode,city_suffix,random_int,numerify,pyint,pyfloat,date,military_dpo,time,catch_phrase,credit_card_full,mime_type,secondary_address
0,aqua,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
1,black,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,application/octet-stream,5
2,blue,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
3,fuchsia,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
4,gray,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
5,green,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
6,lime,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
7,maroon,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
8,navy,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
9,olive,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
10,purple,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
11,silver,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
12,teal,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,application/octet-stream,5
13,white,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
14,yellow,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3

,md5,ean,iban,pystr,ascii_free_email,pybool,postcode,city_suffix,safe_color_name,random_int,numerify,pyint,pyfloat,date,military_dpo,time,catch_phrase,credit_card_full,mime_type,secondary_address
0,a95a7eb3f21c1274a4b3f48afd80198b,2794803323395,GB88ODDR09212117545086,ORBUxoGYWFVRMTuhATYN,wilsonlogan@hotmail.com,True,4871,haven,aqua,4858.0,790.0,3207.0,-6.293333e+07,1984-05-05,Unit 4769 Box 1285,19:50:22,Customizable modular success,Mastercard\nRebecca Martinez\n2221553165505931...,model/vrml,Suite 248
1,7b843a2634d5699b6b76ea3f02bdafed,9857981337547,GB11BUCE56238105840278,TWINbLidkIeERvsoPIan,oduarte@hotmail.com,True,23335,haven,white,3377.0,197.0,6804.0,-4.508725e+00,2001-07-04,Unit 1596 Box 6718,00:56:59,Balanced modular intranet,American Express\nChristopher Salas\n346625186...,text/css,Suite 478
2,60e46ab28bd2f01c7bd2e95b8de670c0,9343065254645,GB34EMPQ77868655294867,keipzkadCrbbCVLNwMVA,mejiaandrew@hotmail.com,True,74076,town,olive,2692.0,726.0,6260.0,1.368254e+06,2017-08-25,Unit 7534 Box 8467,20:11:43,Right-sized foreground database,Mastercard\nRebekah Jacobson\n2221918103085090...,image/gif,Apt. 712
3,b2dd0efb8e8db90ecac22275e7116183,2961643818811,GB67NLCX91988812113431,wDPaePQIMCgEwFDKQHCg,hallangela@hotmail.com,False,38904,shire,yellow,9444.0,594.0,6331.0,7.338699e+01,1984-02-08,Unit 0661 Box 3555,20:59:29,Phased actuating emulation,Discover\nConnor Roth\n6509948363636716 01/27\...,image/svg+xml,Suite 951
4,19489b9412587c4311e7434ce6ba0a71,6601104178660,GB33TKKF58069918658383,NtwoSJEmcmlaFcVMsyGb,gloria51@yahoo.com,False,20553,land,gray,2560.0,927.0,7944.0,2.350744e+07,1983-06-05,Unit 6972 Box 9925,02:57:20,Cloned even-keeled matrix,VISA 16 digit\nDebra Long\n4670461732817635 02...,model/mesh,Suite 827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,bfc3d0a2f77f1ba0725b5c2cb3aba6c3,8262798349231,GB40JYGM93842791742722,lFocpkxeBTDieKAzNiTn,krystal60@hotmail.com,True,91300,borough,white,6244.0,859.0,592.0,6.485426e+11,1982-04-09,Unit 8848 Box 2567,18:01:56,Proactive holistic infrastructure,JCB 16 digit\nNicholas Mccoy\n3517104405528050...,audio/mp4,Apt. 170
96,d2c677e2c32a1c16291c3688a520d011,3432668204471,GB11OEOB46713349407717,DTQyUqhKOkNEJPvxjUHy,carlos15@hotmail.com,False,52160,mouth,teal,981.0,403.0,1810.0,-7.412762e+03,2002-12-07,Unit 6620 Box 9472,18:26:19,Persevering zero administration time-frame,Diners Club / Carte Blanche\nShane Reynolds\n3...,model/x3d+xml,Suite 478
97,5e8be59f5a532221512a84beea0fe424,2693965564656,GB02OBKX35865770744517,YHkmTsXgTSDjFBSZXZgK,paulpeterson@gmail.com,True,59373,chester,fuchsia,5215.0,335.0,2248.0,-7.839509e+11,2011-10-14,Unit 5309 Box 9820,19:58:59,Adaptive bifurcated archive,JCB 16 digit\nCheryl Nelson\n3595216676793315 ...,video/mpeg,Apt. 023
98,87f0917efffa568ca2db3ae04ef5a7cf,8952071337672,GB78GIJB26645390706947,sOmyTAhvOFKZiqJQdVxC,silvacindy@yahoo.com,False,13578,fort,lime,6596.0,388.0,7159.0,-2.739673e+11,1987-01-30,Unit 9639 Box 4616,06:11:10,Operative real-time toolset,JCB 16 digit\nAlbert Murphy\n3555777020813099 ...,multipart/mixed,Suite 322
99,68ffdf707c937dda481189fb0c846831,120864044405,GB21GAGM16853863171062,VbIMCWSioHgVwJOKrQIZ,mitchellmariah@yahoo.com,False,35973,furt,white,7782.0,215.0,1350.0,-9.872482e+05,1994-06-24,Unit 0310 Box 4708,06:15:32,Compatible even-keeled encryption,JCB 15 digit\nAlicia Saunders\n213148391030178...,multipart/encrypted,Apt. 165

In [49]:
# Manual groupby score inspection
import nppo
nppo.df_groupby_check_new(src, dst,df_dict, None, debug=True)

Groupcols ['language_code']
agg_cols ['ean', 'postcode_in_state', 'safe_color_name', 'pyint', 'ein', 'pybool', 'postcode', 'secondary_address', 'paragraph', 'numerify', 'ascii_free_email', 'date', 'tld', 'mime_type', 'file_name', 'md5', 'military_dpo', 'iban', 'pyfloat', 'random_int', 'time', 'city_suffix', 'catch_phrase', 'credit_card_full', 'randomize_nb_elements', 'pystr']
missing_vals 0.0
final_val = (1.0 * len(group_cols) * group_keyness_ratio) - missing_vals * column_diff
1.0  =  (1.0 * 1 * 1.0 )- 0.0 * 1.0

1.0

In [16]:
df_dict['9.csv'].groupby('md5').max()

,safe_color_name,ean,iban,pystr,ascii_free_email,pybool,postcode,city_suffix,random_int,numerify,pyint,pyfloat,date,military_dpo,time,catch_phrase,credit_card_full,mime_type,secondary_address
md5,,,,,,,,,,,,,,,,,,,
3,yellow,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
4,gray,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
5,teal,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
6,silver,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
8,lime,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
10,olive,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10

In [23]:
# Statistics for GB detector

from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay


def plot_edge_cf(cf, title='Edge Confusion Matrix', x='Inferred Edge', y='Ground Truth Edge'):
    disp = ConfusionMatrixDisplay(confusion_matrix=cf,
                                  display_labels=['False', 'True'])


    # NOTE: Fill all variables here with default values of the plot_confusion_matrix
    disp = disp.plot(values_format = '.0f')
    plt.title(title)
    plt.xlabel(x)
    plt.ylabel(y)
    plt.xticks(np.arange(2), ['Negative', 'Positive'])

plt.show()

In [24]:
all_results['true_groupby'] = all_results.apply(lambda x : x.operation == 'groupby', axis=1)
intra_cluster_edges = all_results.loc[all_results.same_cluster]
all_cf = confusion_matrix(intra_cluster_edges.true_groupby, intra_cluster_edges.g_inferred)
all_cf

array([[1276,  124],
       [   9,  168]])

In [25]:
all_results.groupby('operation').count()

,edge,nb,artifacts,groupby,cross_comp,cross_comp_label,contraction_ratio,ground_truth,g_inferred,type,same_cluster,true_groupby
operation,,,,,,,,,,,,
assign,262,262,262,0,262,262,0,262,262,0,262,262
dropcol,356,356,356,0,356,356,0,356,356,0,356,356
groupby,177,177,177,177,177,177,169,177,177,168,177,177
merge,532,532,532,0,532,532,0,532,532,0,532,532
pivot,230,230,230,0,230,230,0,230,230,0,230,230
point_edit,300,300,300,300,300,300,0,300,300,0,300,300
sample,296,296,296,296,296,296,2,296,296,2,296,296

In [27]:
import qgrid
ops_per_nb = all_results.groupby(['nb','operation']).count()
qgrid_widget = qgrid.show_grid(ops_per_nb, show_toolbar=True)
qgrid_widget

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': True, 'defau…

In [30]:
groupby_edges = all_results.loc[all_results.type == 'groupby']
groupby_edges.groupby('operation').count()

,edge,nb,artifacts,groupby,cross_comp,cross_comp_label,contraction_ratio,ground_truth,g_inferred,type,same_cluster,true_groupby
operation,,,,,,,,,,,,
groupby,168,168,168,168,168,168,160,168,168,168,168,168
sample,2,2,2,2,2,2,2,2,2,2,2,2

In [29]:
false_gb = groupby_edges.loc[groupby_edges.true_groupby == False]
false_gb.groupby('nb').count()

,edge,artifacts,groupby,cross_comp,cross_comp_label,contraction_ratio,ground_truth,operation,g_inferred,type,same_cluster,true_groupby
nb,,,,,,,,,,,,
20200817-125817,5,5,5,5,5,5,5,0,5,5,5,5
20200817-125822,1,1,1,1,1,1,1,0,1,1,1,1
20200817-125827,5,5,5,5,5,5,5,0,5,5,5,5
20200817-125831,5,5,5,5,5,5,5,0,5,5,5,5
20200817-125834,2,2,2,2,2,2,2,0,2,2,2,2
20200817-130017,2,2,2,2,2,2,2,0,2,2,2,2
20200817-130033,1,1,1,1,1,1,1,0,1,1,1,1
20200817-130038,1,1,1,1,1,1,1,0,1,1,1,1
20200817-130045,6,6,6,6,6,6,6,0,6,6,6,6
20200817-130055,4,4,4,4,4,4,4,0,4,4,4,4
20200817-130103,1,1,1,1,1,1,1,0,1,1,1,1
20200817-130201,1,1,1,1,1,1,1,0,1,1,1,1
20200817-130257,2,2,2,2,2,2,2,0,2,2,2,2
20200817-130323,3,3,3,3,3,3,3,0,3,3,3,3
20200817-130355,3,3,3,3,3,3,3,0,3,3,3,3
20200817-130409,1,1,1,1,1,1,1,0,1,1,1,1
20200817-130432,3,3,3,3,3,3,3,1,3,3,3,3
20200817-130559,1,1,1,1,1,1,1,0,1,1,1,1
20200817-135030,2,2,2,2,2,2,2,0,2,2,2,2
20200817-135045,2,2,2,2,2,2,2,0,2,2,2,2
20200817-135053,2,2,2,2,2,2,2,0,2,2,2,2
20200817-135057,2,2,2,2,2,2,2,0,2,2,2,2
20200817-135100,1,1,1,1,1,1,1,0,1,1,1,1
20200817-135112,2,2,2,2,2,2,2,0,2,2,2,2
20200817-135121,6,6,6,6,6,6,6,0,6,6,6,6
20200817-135126,4,4,4,4,4,4,4,0,4,4,4,4
20200817-135130,4,4,4,4,4,4,4,0,4,4,4,4
20200817-135135,1,1,1,1,1,1,1,0,1,1,1,1
20200817-135245,1,1,1,1,1,1,1,0,1,1,1,1
20200817-135257,7,7,7,7,7,7,7,0,7,7,7,7
20200817-135331,1,1,1,1,1,1,1,0,1,1,1,1
20200817-140004,2,2,2,2,2,2,2,0,2,2,2,2
20200817-140337,5,5,5,5,5,5,5,0,5,5,5,5
20200817-140352,7,7,7,7,7,7,7,0,7,7,7,7
20200817-141025,3,3,3,3,3,3,3,1,3,3,3,3
20200817-141044,1,1,1,1,1,1,1,0,1,1,1,1
20200817-141508,2,2,2,2,2,2,2,0,2,2,2,2
20200817-141524,4,4,4,4,4,4,4,0,4,4,4,4
20200817-141544,4,4,4,4,4,4,4,0,4,4,4,4
20200817-141622,5,5,5,5,5,5,5,0,5,5,5,5
20200817-141746,3,3,3,3,3,3,3,0,3,3,3,3
20200817-141834,1,1,1,1,1,1,1,0,1,1,1,1
20200817-141902,5,5,5,5,5,5,5,0,5,5,5,5

# Results Enuemration

Groupby: Total: 526
Found by Groupby (True Positive): 496
Missed (False Negative): 30
Mistakes (False Positive): 165 -> Of which 8 were sample edges

Next Task: Explore High False positive Rate. (Could be synthetic generation hicup). After that, check false negative reasons (scoring problem vs. not in "joinable components").

Keep track of all candidate ties.

# DEBUG Section

In [158]:
# Single Instance of Algorithm on nb:
i = notebooks.index('20200802-225935')
nb = notebooks[i]
rl = RelicAlgorithm(RESULT_DIR, nb)
rl.set_initial_clusters()
rl.compute_intra_cluster_edges(weight_label='groupby')
rl.compute_component_pairs()
df = rl.compute_component_link_edges()
df.index

__init__():24 :INFO : Starting instance of RelicAlgorithm on 20200802-225935

Index([('13.csv', '21.csv'),   ('7.csv', '8.csv'),  ('7.csv', '14.csv'),
         ('7.csv', '3.csv'), ('39.csv', '41.csv'), ('12.csv', '23.csv'),
       ('44.csv', '49.csv'), ('21.csv', '11.csv'), ('52.csv', '53.csv'),
       ('50.csv', '49.csv'),  ('12.csv', '8.csv'), ('33.csv', '43.csv'),
       ('61.csv', '60.csv'), ('58.csv', '57.csv'), ('59.csv', '57.csv'),
       ('60.csv', '57.csv'), ('59.csv', '62.csv'), ('48.csv', '47.csv'),
       ('12.csv', '14.csv'), ('34.csv', '47.csv'),   ('1.csv', '0.csv'),
        ('12.csv', '3.csv')],
      dtype='object')

In [168]:
# Developing cross comp max as a tie breaker:
rl.weight_df.iloc[0].name

frozenset({'13.csv', '9.csv'})

In [156]:
rl.infer_link_edges(max_step=10)

infer_link_edges():202 :INFO : Adding edge #1: ['1.csv', '0.csv'], type groupby, weight 1.000000
infer_link_edges():202 :INFO : Adding edge #2: ['34.csv', '47.csv'], type groupby, weight 1.000000
infer_link_edges():202 :INFO : Adding edge #3: ['12.csv', '14.csv'], type groupby, weight 1.000000
infer_link_edges():202 :INFO : Adding edge #4: ['48.csv', '47.csv'], type groupby, weight 1.000000
infer_link_edges():202 :INFO : Adding edge #5: ['59.csv', '62.csv'], type groupby, weight 1.000000
infer_link_edges():202 :INFO : Adding edge #6: ['60.csv', '57.csv'], type groupby, weight 1.000000
infer_link_edges():202 :INFO : Adding edge #7: ['59.csv', '57.csv'], type groupby, weight 1.000000
infer_link_edges():202 :INFO : Adding edge #8: ['58.csv', '57.csv'], type groupby, weight 1.000000
infer_link_edges():202 :INFO : Adding edge #9: ['61.csv', '60.csv'], type groupby, weight 1.000000
infer_link_edges():202 :INFO : Adding edge #10: ['33.csv', '43.csv'], type groupby, weight 1.000000

In [157]:
df = rl.weight_df
cross_comp_edges = df.loc[(df.cross_comp == True) & (df['groupby'] >= 1.0)]
#cross_comp_edges.groupby('cross_comp_label').max()
cross_comp_edges.sort_values('cross_comp_label')

,nb,artifacts,groupby,cross_comp,cross_comp_label
"(12.csv, 23.csv)",20200802-225935,63,1.0,True,12.csv23.csv
"(12.csv, 8.csv)",20200802-225935,63,1.0,True,12.csv8.csv
"(13.csv, 21.csv)",20200802-225935,63,1.0,True,13.csv21.csv
"(21.csv, 11.csv)",20200802-225935,63,1.0,True,21.csv11.csv
"(39.csv, 41.csv)",20200802-225935,63,1.0,True,39.csv41.csv
"(44.csv, 49.csv)",20200802-225935,63,1.0,True,44.csv49.csv
"(50.csv, 49.csv)",20200802-225935,63,1.0,True,50.csv49.csv
"(52.csv, 53.csv)",20200802-225935,63,1.0,True,52.csv53.csv
"(7.csv, 14.csv)",20200802-225935,63,1.0,True,7.csv12.csv
"(7.csv, 3.csv)",20200802-225935,63,1.0,True,7.csv12.csv
"(7.csv, 8.csv)",20200802-225935,63,1.0,True,7.csv8.csv

In [7]:
rl.weight_df.reset_index()

,index,groupby,cross_comp,cross_comp_label,ground_truth,operation,g_inferred,type
0,"(13.csv, 9.csv)",NaN,True,13.csv14.csv,False,NaN,False,NaN
1,"(7.csv, 13.csv)",NaN,True,7.csv13.csv,False,NaN,False,NaN
2,"(15.csv, 13.csv)",NaN,True,15.csv13.csv,False,NaN,False,NaN
3,"(13.csv, 23.csv)",NaN,True,13.csv23.csv,False,NaN,False,NaN
4,"(13.csv, 21.csv)",NaN,True,13.csv19.csv,False,NaN,False,NaN
...,...,...,...,...,...,...,...,...
346,"(10.csv, 1.csv)",NaN,True,10.csv1.csv,False,NaN,False,NaN
347,"(10.csv, 3.csv)",NaN,True,10.csv3.csv,False,NaN,False,NaN
348,"(1.csv, 26.csv)",NaN,True,1.csv26.csv,False,NaN,False,NaN
349,"(3.csv, 26.csv)",NaN,True,3.csv26.csv,False,NaN,False,NaN
350,"(3.csv, 1.csv)",NaN,True,3.csv1.csv,False,NaN,False,NaN

In [3]:
logger.debug('DEBUG')
logger.info('INFO')
logger.warning('WARN')
logger.error('ERROR')

2020-08-11 22:21:06,705 | INFO : INFO
2020-08-11 22:21:06,705 | WARNING : WARN
2020-08-11 22:21:06,706 | ERROR : ERROR

In [7]:
rl.initialize_components()
[x for x in rl.components.to_sets()]

[{'13.csv'},
 {'9.csv'},
 {'7.csv'},
 {'15.csv'},
 {'23.csv'},
 {'21.csv'},
 {'8.csv'},
 {'18.csv'},
 {'17.csv'},
 {'2.csv'},
 {'22.csv'},
 {'19.csv'},
 {'6.csv'},
 {'24.csv'},
 {'14.csv'},
 {'5.csv'},
 {'20.csv'},
 {'25.csv'},
 {'16.csv'},
 {'11.csv'},
 {'4.csv'},
 {'0.csv'},
 {'12.csv'},
 {'10.csv'},
 {'26.csv'},
 {'1.csv'},
 {'3.csv'}]

In [111]:
rl.infer_link_edges()

<networkx.utils.union_find.UnionFind object at 0x7f1063a98970>
[{'13.csv'}, {'9.csv'}, {'7.csv'}, {'15.csv'}, {'23.csv'}, {'21.csv'}, {'8.csv'}, {'18.csv'}, {'17.csv'}, {'2.csv'}, {'22.csv'}, {'19.csv'}, {'6.csv'}, {'24.csv'}, {'14.csv'}, {'5.csv'}, {'20.csv'}, {'25.csv'}, {'16.csv'}, {'11.csv'}, {'4.csv'}, {'1.csv', '0.csv'}, {'12.csv'}, {'10.csv'}, {'26.csv'}, {'3.csv'}]
<networkx.utils.union_find.UnionFind object at 0x7f1063a98970>
[{'13.csv'}, {'9.csv'}, {'7.csv'}, {'15.csv'}, {'23.csv'}, {'21.csv'}, {'8.csv'}, {'18.csv'}, {'17.csv'}, {'2.csv'}, {'22.csv'}, {'19.csv'}, {'6.csv'}, {'24.csv'}, {'14.csv', '11.csv'}, {'5.csv'}, {'20.csv'}, {'25.csv'}, {'16.csv'}, {'4.csv'}, {'1.csv', '0.csv'}, {'12.csv'}, {'10.csv'}, {'26.csv'}, {'3.csv'}]
<networkx.utils.union_find.UnionFind object at 0x7f1063a98970>
[{'13.csv'}, {'9.csv'}, {'7.csv'}, {'15.csv'}, {'23.csv'}, {'21.csv'}, {'8.csv'}, {'18.csv'}, {'17.csv'}, {'2.csv'}, {'22.csv'}, {'19.csv'}, {'5.csv', '6.csv'}, {'24.csv'}, {'14.csv', '11.csv'}, {'20.csv'}, {'25.csv'}, {'16.csv'}, {'4.csv'}, {'1.csv', '0.csv'}, {'12.csv'}, {'10.csv'}, {'26.csv'}, {'3.csv'}]
<networkx.utils.union_find.UnionFind object at 0x7f1063a98970>
[{'13.csv'}, {'9.csv'}, {'7.csv'}, {'15.csv'}, {'23.csv'}, {'21.csv', '19.csv'}, {'8.csv'}, {'18.csv'}, {'17.csv'}, {'2.csv'}, {'22.csv'}, {'5.csv', '6.csv'}, {'24.csv'}, {'14.csv', '11.csv'}, {'20.csv'}, {'25.csv'}, {'16.csv'}, {'4.csv'}, {'1.csv', '0.csv'}, {'12.csv'}, {'10.csv'}, {'26.csv'}, {'3.csv'}]
<networkx.utils.union_find.UnionFind object at 0x7f1063a98970>
[{'13.csv'}, {'9.csv', '14.csv', '11.csv'}, {'7.csv'}, {'15.csv'}, {'23.csv'}, {'21.csv', '19.csv'}, {'8.csv'}, {'18.csv'}, {'17.csv'}, {'2.csv'}, {'22.csv'}, {'5.csv', '6.csv'}, {'24.csv'}, {'20.csv'}, {'25.csv'}, {'16.csv'}, {'4.csv'}, {'1.csv', '0.csv'}, {'12.csv'}, {'10.csv'}, {'26.csv'}, {'3.csv'}]

In [112]:
#rl.update_components()
[x for x in rl.components.to_sets()]

[{'13.csv'},
 {'11.csv', '14.csv', '9.csv'},
 {'7.csv'},
 {'15.csv'},
 {'23.csv'},
 {'19.csv', '21.csv'},
 {'8.csv'},
 {'18.csv'},
 {'17.csv'},
 {'2.csv'},
 {'22.csv'},
 {'5.csv', '6.csv'},
 {'24.csv'},
 {'20.csv'},
 {'25.csv'},
 {'16.csv'},
 {'4.csv'},
 {'0.csv', '1.csv'},
 {'12.csv'},
 {'10.csv'},
 {'26.csv'},
 {'3.csv'}]

In [113]:
rl.compute_component_pairs()

                  groupby  cross_comp cross_comp_label
(9.csv, 13.csv)       NaN        True     14.csv13.csv
(13.csv, 7.csv)       NaN        True      13.csv7.csv
(15.csv, 13.csv)      NaN        True     15.csv13.csv
(23.csv, 13.csv)      NaN        True     23.csv13.csv
(21.csv, 13.csv)      NaN        True     21.csv13.csv
...                   ...         ...              ...
(10.csv, 1.csv)       NaN        True      10.csv1.csv
(10.csv, 3.csv)       NaN        True      10.csv3.csv
(1.csv, 26.csv)       NaN        True      1.csv26.csv
(3.csv, 26.csv)       NaN        True      3.csv26.csv
(1.csv, 3.csv)        NaN        True       1.csv3.csv

[351 rows x 3 columns]

In [114]:
rl.g_inferred.edges()

EdgeView([('9.csv', '11.csv'), ('21.csv', '19.csv'), ('6.csv', '5.csv'), ('14.csv', '11.csv'), ('0.csv', '1.csv')])

In [74]:
rl.components

TypeError: 'UnionFind' object is not callable

In [51]:
# Similar Node Exploration

import pickle 

nb = nb_name
with open(RESULT_DIR+'/'+nb+'/'+nb+'_gt_similar_nodes.pkl', 'rb') as handle:
    sim_dict = pickle.load(handle)

In [52]:
sim_dict

{(1, '2'): [0],
 (0, '3'): [1],
 (6, '9'): [7],
 (10, '11'): [9],
 (14, '15'): [13],
 (12, '16'): [13, 14],
 (10, '17'): [9]}

In [23]:
df = df2[['safe_color_name', 'mime_type', 'pyint', 'numerify']]
df

   safe_color_name            mime_type   pyint  numerify
0             aqua           model/vrml  3207.0     790.0
1            white             text/css  6804.0     197.0
2            olive            image/gif  6260.0     726.0
3           yellow        image/svg+xml  6331.0     594.0
4             gray           model/mesh  7944.0     927.0
..             ...                  ...     ...       ...
95           white            audio/mp4   592.0     859.0
96            teal        model/x3d+xml  1810.0     403.0
97         fuchsia           video/mpeg  2248.0     335.0
98            lime      multipart/mixed  7159.0     388.0
99           white  multipart/encrypted  1350.0     215.0

[100 rows x 4 columns]

In [27]:
df_grouped = df.groupby('safe_color_name').sum()
df_grouped

                   pyint  numerify
safe_color_name
aqua             53465.0    5872.0
black            31624.0    2857.0
blue             43961.0    3782.0
fuchsia          17208.0    1076.0
gray             39892.0    3772.0
green            16564.0    3085.0
lime             40210.0    2683.0
maroon           23111.0    1156.0
navy             24128.0    2576.0
olive            46414.0    4798.0
purple           48104.0    3999.0
silver           45436.0    2863.0
teal             27314.0    3903.0
white            23148.0    3028.0
yellow           21993.0    2930.0

In [30]:
df_drop = df.drop('mime_type',axis=1)
df_drop.groupby('safe_color_name').sum()

                   pyint  numerify
safe_color_name
aqua             53465.0    5872.0
black            31624.0    2857.0
blue             43961.0    3782.0
fuchsia          17208.0    1076.0
gray             39892.0    3772.0
green            16564.0    3085.0
lime             40210.0    2683.0
maroon           23111.0    1156.0
navy             24128.0    2576.0
olive            46414.0    4798.0
purple           48104.0    3999.0
silver           45436.0    2863.0
teal             27314.0    3903.0
white            23148.0    3028.0
yellow           21993.0    2930.0